import Foundation

/// The app-facing contract for resolving a video into short-lived playback
/// sources. Provider-specific response models must never cross this boundary.
protocol PlaybackResolving: Sendable {
    func resolve(_ request: PlaybackRequest) async throws -> ResolvedPlaybackSource
}

struct PlaybackRequest: Hashable, Sendable {
    let videoID: String
    let languageCode: String
    let regionCode: String
    let networkPolicy: NetworkRequestPolicy

    init(
        videoID: String,
        languageCode: String = Locale.current.language.languageCode?.identifier ?? "en",
        regionCode: String = Locale.current.region?.identifier ?? "US",
        networkPolicy: NetworkRequestPolicy = .interactive
    ) {
        self.videoID = videoID
        self.languageCode = languageCode
        self.regionCode = regionCode
        self.networkPolicy = networkPolicy
    }

    /// Content is independent of network permission; in-flight work is not.
    var cacheKey: PlaybackRequest {
        PlaybackRequest(videoID: videoID, languageCode: languageCode, regionCode: regionCode)
    }
}

struct ResolvedPlaybackSource: Sendable {
    let videoID: String
    let variants: [PlaybackVariant]
    let captions: [PlaybackCaptionTrack]
    let capabilities: PlaybackCapabilities
    let resolvedAt: Date
    let expiresAt: Date

    /// HLS is preferred because AVPlayer can select and switch its variants.
    /// For progressive sources, prefer the best combined stream available.
    var preferredVariant: PlaybackVariant? {
        variants.first(where: { $0.transport == .hls })
            ?? variants.max(by: { $0.qualitySortValue < $1.qualitySortValue })
    }

    func isFresh(at date: Date = .now, refreshLeeway: TimeInterval = 120) -> Bool {
        expiresAt.timeIntervalSince(date) > refreshLeeway
    }
}

struct PlaybackVariant: Identifiable, Hashable, Sendable {
    enum Transport: String, Sendable {
        case hls
        case progressive
    }

    let id: String
    let url: URL
    let transport: Transport
    let qualityLabel: String?
    let width: Int?
    let height: Int?
    let bitrate: Int?
    let mimeType: String
    let expiresAt: Date

    fileprivate var qualitySortValue: Int {
        let pixels = (width ?? 0) * (height ?? 0)
        return pixels > 0 ? pixels : (bitrate ?? 0)
    }
}

struct PlaybackCaptionTrack: Identifiable, Hashable, Sendable {
    let id: String
    let languageCode: String
    let displayName: String
    let url: URL
    let isAutoGenerated: Bool
    let isTranslatable: Bool
}

/// Provider-neutral diagnostics used to decide whether native playback has
/// sufficient coverage before the current embedded fallback is removed.
struct PlaybackCapabilities: Sendable {
    let allQualityLabels: [String]
    let nativeQualityLabels: [String]
    let separateTrackQualityLabels: [String]
    let hasAdaptiveHLS: Bool
    let hasCaptions: Bool
    let cipheredFormatCount: Int
}

enum PlaybackResolverError: LocalizedError, Sendable {
    case invalidVideoID
    case configurationUnavailable
    case invalidResponse(statusCode: Int?, reason: String?)
    case videoUnavailable(status: String, reason: String?)
    case unsupportedLiveContent
    case noCompatibleSource(capabilities: PlaybackCapabilities)

    var errorDescription: String? {
        switch self {
        case .invalidVideoID:
            return "The video ID is invalid."
        case .configurationUnavailable:
            return "Playback configuration is temporarily unavailable."
        case let .invalidResponse(statusCode, reason):
            return [
                "INVALID_RESPONSE",
                statusCode.map { "HTTP \($0)" },
                reason
            ]
            .compactMap { $0 }
            .joined(separator: " · ")
        case let .videoUnavailable(status, reason):
            return [status, reason ?? "This video is unavailable."]
                .joined(separator: " · ")
        case .unsupportedLiveContent:
            return "Live and upcoming videos are not supported by native playback yet."
        case let .noCompatibleSource(capabilities):
            let all = capabilities.allQualityLabels.joined(separator: ", ")
            let native = capabilities.nativeQualityLabels.joined(separator: ", ")
            let separate = capabilities.separateTrackQualityLabels.joined(separator: ", ")
            return """
            NO_COMPATIBLE_SOURCE · Available: \(all.isEmpty ? "none" : all) ·             Native combined: \(native.isEmpty ? "none" : native) ·             Separate only: \(separate.isEmpty ? "none" : separate) ·             HLS: \(capabilities.hasAdaptiveHLS ? "yes" : "no") ·             Ciphered: \(capabilities.cipheredFormatCount)
            """
        }
    }
}

extension ResolvedPlaybackSource {
    /// Badges for what the stream offers: the highest resolution, HDR and
    /// captions (SDH when a caption track is marked as such).
    var technicalBadges: [String] {
        let labels = capabilities.allQualityLabels
        var badges: [String] = []

        let heights = labels.compactMap { Int($0.prefix(while: \.isNumber)) }
        if let maxHeight = heights.max() {
            switch maxHeight {
            case 4320...: badges.append("8K")
            case 2160...: badges.append("4K")
            case 720...: badges.append("HD")
            default: badges.append("SD")
            }
        }
        if labels.contains(where: { $0.uppercased().contains("HDR") }) {
            badges.append("HDR")
        }
        if !captions.isEmpty {
            badges.append("CC")
        }
        if captions.contains(where: { $0.displayName.uppercased().contains("SDH") }) {
            badges.append("SDH")
        }
        return badges
    }
}
