import Foundation

/// The app-facing contract for resolving a video into short-lived playback
/// sources. Provider-specific response models must never cross this boundary.
protocol PlaybackResolving: Sendable {
    func resolve(_ request: PlaybackRequest) async throws -> ResolvedPlaybackSource
}

struct PlaybackRequest: Hashable, Sendable {
    let videoID: String
    let languageCode: String
    let regionCode: String

    init(
        videoID: String,
        languageCode: String = Locale.current.language.languageCode?.identifier ?? "en",
        regionCode: String = Locale.current.region?.identifier ?? "US"
    ) {
        self.videoID = videoID
        self.languageCode = languageCode
        self.regionCode = regionCode
    }
}

struct ResolvedPlaybackSource: Sendable {
    let videoID: String
    let variants: [PlaybackVariant]
    let captions: [PlaybackCaptionTrack]
    let capabilities: PlaybackCapabilities
    let resolvedAt: Date
    let expiresAt: Date

    /// HLS is preferred because AVPlayer can select and switch its variants.
    /// For progressive sources, prefer the best combined stream available.
    var preferredVariant: PlaybackVariant? {
        variants.first(where: { $0.transport == .hls })
            ?? variants.max(by: { $0.qualitySortValue < $1.qualitySortValue })
    }

    func isFresh(at date: Date = .now, refreshLeeway: TimeInterval = 120) -> Bool {
        expiresAt.timeIntervalSince(date) > refreshLeeway
    }
}

struct PlaybackVariant: Identifiable, Hashable, Sendable {
    enum Transport: String, Sendable {
        case hls
        case progressive
    }

    let id: String
    let url: URL
    let transport: Transport
    let qualityLabel: String?
    let width: Int?
    let height: Int?
    let framesPerSecond: Int?
    let bitrate: Int?
    let mimeType: String
    let codecs: String?
    let isHDR: Bool
    let expiresAt: Date

    fileprivate var qualitySortValue: Int {
        let pixels = (width ?? 0) * (height ?? 0)
        return pixels > 0 ? pixels : (bitrate ?? 0)
    }
}

struct PlaybackCaptionTrack: Identifiable, Hashable, Sendable {
    let id: String
    let languageCode: String
    let displayName: String
    let url: URL
    let isAutoGenerated: Bool
    let isTranslatable: Bool
}

/// Provider-neutral diagnostics used to decide whether native playback has
/// sufficient coverage before the current embedded fallback is removed.
struct PlaybackCapabilities: Sendable {
    let allQualityLabels: [String]
    let nativeQualityLabels: [String]
    let separateTrackQualityLabels: [String]
    let hasAdaptiveHLS: Bool
    let hasCaptions: Bool
    let cipheredFormatCount: Int
}

enum PlaybackResolverError: LocalizedError, Sendable {
    case invalidVideoID
    case configurationUnavailable
    case invalidResponse
    case videoUnavailable(reason: String?)
    case unsupportedLiveContent
    case noCompatibleSource(capabilities: PlaybackCapabilities)

    var errorDescription: String? {
        switch self {
        case .invalidVideoID:
            "The video ID is invalid."
        case .configurationUnavailable:
            "Playback configuration is temporarily unavailable."
        case .invalidResponse:
            "The playback service returned an unreadable response."
        case let .videoUnavailable(reason):
            reason ?? "This video is unavailable."
        case .unsupportedLiveContent:
            "Live and upcoming videos are not supported by native playback yet."
        case .noCompatibleSource:
            "No combined HLS or MP4 source compatible with native playback was returned."
        }
    }
}
